export const AVATARS: { id: string; label: string }[] = [
  { id: "01_redhead_ponytail", label: "Redhead Ponytail" },
  { id: "02_dark_boy", label: "Dark Boy" },
  { id: "03_brown_cap", label: "Brown Cap" },
  { id: "04_red_cap_boy", label: "Red Cap Boy" },
  { id: "05_huge_glasses", label: "Huge Glasses" },
  { id: "06_cool_glasses_girl", label: "Cool Glasses Girl" },
  { id: "07_dark_girl_stripes", label: "Dark Girl Stripes" },
  { id: "08_headphones_boy", label: "Headphones Boy" },
  { id: "09_pigtails_girl", label: "Pigtails Girl" },
  { id: "10_dark_ponytail", label: "Dark Ponytail" },
  { id: "11_red_cap_girl", label: "Red Cap Girl" },
  { id: "12_blonde_headband", label: "Blonde Headband" },
  { id: "14_blonde_yellow", label: "Blonde Yellow" },
  { id: "15_glasses_boy", label: "Glasses Boy" },
  { id: "16_dark_smirk", label: "Dark Smirk" },
  { id: "17_red_hair_girl", label: "Red Hair Girl" },
  { id: "18_long_blonde", label: "Long Blonde" },
  { id: "19_brown_longhair", label: "Brown Long Hair" },
  { id: "20_dark_afro1", label: "Dark Afro 1" },
  { id: "21_dark_afro2", label: "Dark Afro 2" },
  { id: "22_blonde_tiny", label: "Blonde Tiny" },
  { id: "23_red_pigtail", label: "Red Pigtail" },
  { id: "24_dark_short_girl", label: "Dark Short Girl" },
  { id: "25_dark_bowl", label: "Dark Bowl" },
  { id: "26_dark_bow_pigtails", label: "Dark Bow Pigtails" },
  { id: "27_curly_brown", label: "Curly Brown" },
  { id: "28_yellow_cap", label: "Yellow Cap" },
];
